image: registry.gitlab.com/scrumplex/docker-archlinux:latest

prepare:
  stage: .pre
  script:
    - pacman -Syu --noconfirm --noprogressbar
    - pacman -S --noconfirm --noprogressbar libxnctrl libxrandr cmake check

build:
  stage: build
  before_script:
    - cmake -B build
  script:
    - make -C build


test:
  stage: test
  script:
    - make -C build test
